language: python

python:
  - 3.6

install: 
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev xvfb mplayer lame git
  - pip install PyQt5 sip pytest
  - start-stop-daemon --start --pidfile ~/xvfb.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset
  - export DISPLAY=:99

script:
  - bash tools/test.sh
